[package]
name = "experimental_component_model-bindings"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
"wit-bindgen" = { version = "0.4.0", features = ["realloc"], default-features = false }
